version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_API_NAME=${CLOUDINARY_API_NAME}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped